apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/instance
  labels:
    testing.kubedb.com/example-name: example-dbinstance
  name: example
spec:
  forProvider:
    region: us-east-2
    engine: mysql
    engineVersion: "8.0.33"
    username: adminuser
    dbName: dbexample
    #autoGeneratePassword: true
    passwordSecretRef:
      key: password
      name: example-dbinstance
      namespace: crossplane-system
    instanceClass: db.t3.micro
    storageType: gp2
    allocatedStorage: 20
    dbSubnetGroupName: example
    kmsKeyIdRef:
      name: sample-key
    backupRetentionPeriod: 0
    backupWindow: "09:46-10:16"
    maintenanceWindow: "Mon:00:00-Mon:03:00"
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageEncrypted: true
    autoMinorVersionUpgrade: true
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: default
---

apiVersion: kms.aws.kubedb.com/v1alpha1
kind: Key
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/instance
  labels:
    testing.kubedb.com/example-name: sample-key
  name: sample-key
spec:
  forProvider:
    region: us-east-2
    description: Created with Crossplane
    deletionWindowInDays: 7

---
apiVersion: v1
kind: Secret
metadata:
  name: example-dbinstance
  namespace: crossplane-system
type: Opaque
data:
  password: MTIzNDU2Nzg=
  #12345678


---

apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: VPC
metadata:
  name: example
spec:
  forProvider:
    region: us-east-2
    cidrBlock: 172.16.0.0/16
    tags:
      Name: DemoVpc

---

apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: Subnet
metadata:
  name: example-subnet1
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2b
    vpcIdRef:
      name: example
    cidrBlock: 172.16.10.0/24

---

apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: Subnet
metadata:
  name: example-subnet2
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2c
    vpcIdRef:
      name: example
    cidrBlock: 172.16.20.0/24

---

apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: Subnet
metadata:
  name: example-subnet3
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2a
    vpcIdRef:
      name: example
    cidrBlock: 172.16.30.0/24

---

apiVersion: rds.aws.kubedb.com/v1alpha1
kind: SubnetGroup
metadata:
  name: example
spec:
  forProvider:
    region: us-east-2
    subnetIdRefs:
      - name: example-subnet1
      - name: example-subnet2
      - name: example-subnet3
    tags:
      Name: My DB subnet group