apiVersion: vpc.aws.kubedb.com/v1alpha1
kind: SecurityGroupIngressRule
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/securitygroupingressrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrIpv4: 10.0.0.0/8
    fromPort: 80
    ipProtocol: tcp
    region: us-west-1
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    toPort: 8080
