apiVersion: kms.aws.kubedb.com/v1alpha1
kind: Key
metadata:
  annotations:
    meta.kubedb.com/example-id: kms/v1alpha1/key
  labels:
    testing.kubedb.com/example-name: a
  name: a
spec:
  forProvider:
    deletionWindowInDays: 10
    description: KMS key 1
    region: us-west-1
