apiVersion: aws.kubedb.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: aws-secret
      key: creds
      namespace: crossplane-system

#  echo '
#  [default]
#  aws_access_key_id = <your_access_key>
#  aws_secret_access_key = <your_secret_access_key>
#  ' > aws-credentials.txt

#  kubectl create secret  generic aws-secret -n crossplane-system --from-file=creds=./aws-credentials.txt