apiVersion: simpledb.aws.kubedb.com/v1alpha1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: simpledb/v1alpha1/domain
  labels:
    testing.upbound.io/example-name: users
  name: users
spec:
  forProvider:
    region: us-west-1
