apiVersion: rds.aws.kubedb.com/v1alpha1
kind: ClusterInstance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/clusterinstance
  labels:
    testing.upbound.io/example-name: cluster_instances
  name: cluster-instances
spec:
  forProvider:
    clusterIdentifier: ${aws_rds_cluster.default.id}
    count: 2
    engine: aurora-mysql
    engineVersion: ${aws_rds_cluster.default.engine_version}
    instanceClass: db.r4.large
    region: us-west-1

---

apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/clusterinstance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    availabilityZones:
    - us-west-2a
    - us-west-2b
    - us-west-2c
    databaseName: mydb
    masterPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    masterUsername: foo
    region: us-west-1

---

