apiVersion: rds.aws.kubedb.com/v1alpha1
kind: ClusterSnapshot
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/clustersnapshot
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    dbClusterIdentifierSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    dbClusterSnapshotIdentifier: resourcetestsnapshot1234
    region: us-west-1
