apiVersion: rds.aws.kubedb.com/v1alpha1
kind: ClusterParameterGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/clusterparametergroup
  labels:
    testing.kubedb.com/example-name: default
  name: default
spec:
  forProvider:
    description: RDS default cluster parameter group
    family: aurora5.6
    parameter:
    - name: character_set_server
      value: utf8
    - name: character_set_client
      value: utf8
    region: us-west-1
