apiVersion: rds.aws.kubeform.com/v1alpha1
kind: DBInstanceAutomatedBackupsReplication
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/dbinstanceautomatedbackupsreplication
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: us-west-1
    retentionPeriod: 14
    sourceDbInstanceArn: arn:aws:rds:us-west-2:123456789012:db:mydatabase

---

