apiVersion: rds.aws.kubedb.com/v1alpha1
kind: DBSnapshotCopy
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/dbsnapshotcopy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    sourceDbSnapshotIdentifier: ${aws_db_snapshot.example.db_snapshot_arn}
    targetDbSnapshotIdentifier: testsnapshot1234-copy

---

apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/dbsnapshotcopy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allocatedStorage: 10
    backupRetentionPeriod: 0
    dbName: baz
    engine: mysql
    engineVersion: 5.6.21
    instanceClass: db.t2.micro
    maintenanceWindow: Fri:09:00-Fri:09:30
    parameterGroupName: default.mysql5.6
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    region: us-west-1
    username: foo

---

apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/dbsnapshotcopy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dbInstanceIdentifier: ${aws_db_instance.example.identifier}
    region: us-west-1

---

