apiVersion: rds.aws.kubedb.com/v1alpha1
kind: EventSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/eventsubscription
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    eventCategories:
    - availability
    - deletion
    - failover
    - failure
    - low storage
    - maintenance
    - notification
    - read replica
    - recovery
    - restoration
    region: us-west-1
    snsTopic: ${aws_sns_topic.default.arn}
    sourceIds:
    - ${aws_db_instance.default.identifier}
    sourceType: db-instance

---

apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/eventsubscription
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allocatedStorage: 10
    dbName: mydb
    dbSubnetGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    engine: mysql
    engineVersion: 5.6.17
    instanceClass: db.t2.micro
    parameterGroupName: default.mysql5.6
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    region: us-west-1
    username: foo
