apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/instance
  labels:
    testing.kubedb.com/example-name: default
  name: default
spec:
  forProvider:
    allocatedStorage: 10
    dbName: mydb
    engine: mysql
    engineVersion: "5.7"
    instanceClass: db.t3.micro
    parameterGroupName: default.mysql5.7
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    region: us-west-1
    skipFinalSnapshot: true
    username: foo
