apiVersion: rds.aws.kubedb.com/v1alpha1
kind: InstanceRoleAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instanceroleassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dbInstanceIdentifier: ${aws_db_instance.example.identifier}
    featureName: S3_INTEGRATION
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

