apiVersion: rds.aws.kubedb.com/v1alpha1
kind: OptionGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/optiongroup
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    engineName: sqlserver-ee
    majorEngineVersion: "11.00"
    option:
    - optionName: Timezone
      optionSettings:
      - name: TIME_ZONE
        value: UTC
    - optionName: SQLSERVER_BACKUP_RESTORE
      optionSettings:
      - name: IAM_ROLE_ARN
        value: ${aws_iam_role.example.arn}
    - optionName: TDE
    optionGroupDescription: Terraform Option Group
    region: us-west-1
