apiVersion: rds.aws.kubedb.com/v1alpha1
kind: ProxyEndpoint
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/proxyendpoint
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    dbProxyNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: test
    region: us-west-1
    targetRole: READ_ONLY
    vpcSubnetIds: ${aws_subnet.test[*].id}
