apiVersion: memorydb.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.kubedb.com/example-id: memorydb/v1alpha1/cluster
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    aclName: open-access
    nodeType: db.t4g.small
    numShards: 2
    region: us-west-1
    securityGroupIdRefs:
    - name: example
    snapshotRetentionLimit: 7
    subnetGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
