apiVersion: memorydb.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: memorydb/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    aclName: open-access
    nodeType: db.t4g.small
    numShards: 2
    region: us-west-1
    securityGroupIdRefs:
    - name: example
    snapshotRetentionLimit: 7
    subnetGroupName: ${aws_memorydb_subnet_group.example.id}

---

