apiVersion: memorydb.aws.kubedb.com/v1alpha1
kind: ParameterGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: memorydb/v1alpha1/parametergroup
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    family: memorydb_redis6
    parameter:
    - name: activedefrag
      value: "yes"
    region: us-west-1
