apiVersion: memorydb.aws.kubedb.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.kubedb.com/example-id: memorydb/v1alpha1/snapshot
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    region: us-west-1
