apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: GlobalCluster
metadata:
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    engine: docdb
    engineVersion: 5.0.0
    globalClusterIdentifier: global-test
---