apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: EventSubscription
metadata:
  annotations:
    meta.kubedb.com/example-id: docdb/v1alpha1/eventsubscription
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    enabled: true
    eventCategories:
    - creation
    - failure
    region: us-east-2
    snsTopicArnSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    sourceType: db-cluster
---
# apiVersion: sns.aws.kubedb.com/v1alpha1
# kind: Topic
# metadata:
#   annotations:
#     meta.kubedb.com/example-id: docdb/v1alpha1/eventsubscription
#   labels:
#     testing.kubedb.com/example-name: example
#   name: example
# spec:
#   forProvider:
#     region: us-east-2

---
