apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: SecurityGroupRule
metadata:
  annotations:
    meta.kubedb.com/example-id: ec2/v1alpha1/securitygrouprule
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    cidrBlocks:
    - ${aws_vpc.example.cidr_block}
    fromPort: 0
    ipv6CidrBlocks:
    - ${aws_vpc.example.ipv6_cidr_block}
    protocol: tcp
    region: us-west-1
    securityGroupIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    toPort: 65535
    type: ingress
