apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.kubedb.com/example-id: ec2/v1alpha1/subnet
  labels:
    testing.kubedb.com/example-name: main
  name: main
spec:
  forProvider:
    cidrBlock: 10.0.1.0/24
    region: us-west-1
    tags:
      Name: Main
    vpcIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: main
