apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-west-1
