apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: VPCEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1alpha1/vpcendpoint
  labels:
    testing.upbound.io/example-name: s3
  name: s3
spec:
  forProvider:
    region: us-west-1
    serviceName: com.amazonaws.us-west-2.s3
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main

---

