apiVersion: appconfig.aws.kubedb.com/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationId: ${aws_appconfig_application.example.id}
    description: Example AppConfig Environment
    monitor:
    - alarmArn: ${aws_cloudwatch_metric_alarm.example.arn}
      alarmRoleArn: ${aws_iam_role.example.arn}
    region: us-west-1
    tags:
      Type: AppConfig Environment
