apiVersion: elasticache.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticache/v1alpha1/cluster
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    engine: memcached
    nodeType: cache.m4.large
    numCacheNodes: 2
    parameterGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    port: 11211
    region: us-west-1
