apiVersion: elasticache.aws.kubedb.com/v1alpha1
kind: ParameterGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticache/v1alpha1/parametergroup
  labels:
    testing.kubedb.com/example-name: default
  name: default
spec:
  forProvider:
    family: redis2.8
    name: cache-params
    parameter:
    - name: activerehashing
      value: "yes"
    - name: min-slaves-to-write
      value: "2"
    region: us-west-1
