apiVersion: elasticache.aws.kubedb.com/v1alpha1
kind: ReplicationGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1alpha1/replicationgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    automaticFailoverEnabled: true
    description: example description
    nodeType: cache.m4.large
    numCacheClusters: 2
    parameterGroupName: default.redis3.2
    port: 6379
    preferredCacheClusterAzs:
    - us-west-2a
    - us-west-2b
    region: us-west-1
