apiVersion: elasticache.aws.kubedb.com/v1alpha1
kind: SubnetGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticache/v1alpha1/subnetgroup
  labels:
    testing.kubedb.com/example-name: bar
  name: bar
spec:
  forProvider:
    region: us-west-1
    subnetIdRefs:
    - name: foo

---

apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticache/v1alpha1/subnetgroup
  labels:
    testing.kubedb.com/example-name: foo
  name: foo
spec:
  forProvider:
    availabilityZone: us-west-2a
    cidrBlock: 10.0.0.0/24
    region: us-west-1
    tags:
      Name: tf-test
    vpcIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: foo

---

apiVersion: ec2.aws.kubedb.com/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticache/v1alpha1/subnetgroup
  labels:
    testing.kubedb.com/example-name: foo
  name: foo
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-west-1
    tags:
      Name: tf-test
