apiVersion: elasticache.aws.kubedb.com/v1alpha1
kind: User
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticache/v1alpha1/user
  labels:
    testing.kubedb.com/example-name: test
  name: test
spec:
  forProvider:
    accessString: on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield
      -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius
      -georadiusbymember
    engine: REDIS
    passwordsSecretRef:
    - key: example-key
      name: example-secret
      namespace: upbound-system
    region: us-west-1
    userName: testUserName
