apiVersion: kinesis.aws.kubedb.com/v1alpha1
kind: Stream
metadata:
  annotations:
    meta.kubedb.com/example-id: kinesis/v1alpha1/stream
  labels:
    testing.kubedb.com/example-name: test_stream
  name: test-stream
spec:
  forProvider:
    region: us-west-1
    retentionPeriod: 48
    shardCount: 1
    shardLevelMetrics:
    - IncomingBytes
    - OutgoingBytes
    streamModeDetails:
    - streamMode: PROVISIONED
    tags:
      Environment: test
