apiVersion: ec2.aws.kubeform.com/v1alpha1
kind: Route
metadata:
  name: test-rt
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    region: us-east-1
    routeTableId: rtb-024c0a2e475286edc
    vpcPeeringConnectionId: pcx-0b932d8f4f56fc701
---

