apiVersion: ec2.aws.kubeform.com/v1alpha1
kind: SecurityGroupRule
metadata:
  name: example
spec:
  forProvider:
    cidrBlocks:
    - ${aws_vpc.example.cidr_block}
    fromPort: 0
    ipv6CidrBlocks:
    - ${aws_vpc.example.ipv6_cidr_block}
    protocol: tcp
    region: us-west-1
    securityGroupId: sg-123456
    toPort: 65535
    type: ingress

---

