apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: ClusterInstance
metadata:
  annotations:
    meta.kubedb.com/example-id: docdb/v1alpha1/clusterinstance
  labels:
    testing.kubedb.com/example-name: cluster_instances
  name: cluster-instances
spec:
  forProvider:
    clusterIdentifierSelector:
      matchLabels:
        testing.kubedb.com/example-name: default
    count: 2
    instanceClass: db.r5.large
    region: us-west-1

---

apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.kubedb.com/example-id: docdb/v1alpha1/clusterinstance
  labels:
    testing.kubedb.com/example-name: default
  name: default
spec:
  forProvider:
    availabilityZones:
    - us-west-2a
    - us-west-2b
    - us-west-2c
    masterPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    masterUsername: foo
    region: us-west-1
