apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: ClusterSnapshot
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/clustersnapshot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dbClusterIdentifierSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
