apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: docdb
  name: docdb
spec:
  forProvider:
    backupRetentionPeriod: 5
    engine: docdb
    masterPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    masterUsername: foo
    preferredBackupWindow: 07:00-09:00
    region: us-west-1
    skipFinalSnapshot: true

---

