apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: GlobalCluster
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/globalcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    engine: docdb
    engineVersion: 4.0.0
    globalClusterIdentifier: global-test
    region: us-west-1

---

apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/globalcluster
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    dbSubnetGroupName: default
    engine: docdb
    engineVersion: 4.0.0
    globalClusterIdentifier: ${aws_docdb_global_cluster.example.id}
    masterPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    masterUsername: username
    provider: ${aws.primary}
    region: us-west-1

---

apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/globalcluster
  labels:
    testing.upbound.io/example-name: secondary
  name: secondary
spec:
  forProvider:
    dbSubnetGroupName: default
    engine: docdb
    engineVersion: 4.0.0
    globalClusterIdentifier: ${aws_docdb_global_cluster.example.id}
    provider: ${aws.secondary}
    region: us-west-1

---

apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: ClusterInstance
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/globalcluster
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    clusterIdentifierSelector:
      matchLabels:
        testing.upbound.io/example-name: primary
    engine: docdb
    instanceClass: db.r5.large
    provider: ${aws.primary}
    region: us-west-1

---

apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: ClusterInstance
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1alpha1/globalcluster
  labels:
    testing.upbound.io/example-name: secondary
  name: secondary
spec:
  forProvider:
    clusterIdentifierSelector:
      matchLabels:
        testing.upbound.io/example-name: secondary
    engine: docdb
    instanceClass: db.r5.large
    provider: ${aws.secondary}
    region: us-west-1
