apiVersion: docdb.aws.kubedb.com/v1alpha1
kind: SubnetGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: docdb/v1alpha1/subnetgroup
  labels:
    testing.kubedb.com/example-name: default
  name: default
spec:
  forProvider:
    region: us-west-1
    subnetIdsRefs:
    - name: frontend
    - name: backend
    tags:
      Name: My docdb subnet group
