apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: ContributorInsights
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/contributorinsights
  labels:
    testing.kubedb.com/example-name: test
  name: test
spec:
  forProvider:
    region: us-west-1
    tableNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
