apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: TableItem
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/tableitem
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    hashKey: ${aws_dynamodb_table.example.hash_key}
    item: |
      {
        "exampleHashKey": {"S": "something"},
        "one": {"N": "11111"},
        "two": {"N": "22222"},
        "three": {"N": "33333"},
        "four": {"N": "44444"}
      }
    region: us-west-1
    tableNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example

---

apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/tableitem
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    readCapacity: 10
    region: us-west-1
    writeCapacity: 10
