apiVersion: rds.aws.kubedb.com/v1alpha1
kind: DBSnapshotCopy
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/dbsnapshotcopy
    upjet.kubedb.com/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    sourceDbSnapshotIdentifierSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    targetDbSnapshotIdentifier: testsnapshot1234-copy
---
apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/dbsnapshotcopy
    upjet.kubedb.com/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    dbInstanceIdentifier: example-dbinstance-1
    region: us-east-2