apiVersion: rds.aws.kubedb.com/v1alpha1
kind: OptionGroup
metadata:
  name: example
spec:
  forProvider:
    region: us-east-2
    engineName: sqlserver-ee
    majorEngineVersion: "11.00"
    option:
      - optionName: TDE
    optionGroupDescription: Kubedb Option Group