apiVersion: rds.aws.kubedb.com/v1alpha1
kind: ClusterParameterGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: rds/v1alpha1/parametergroup
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    family: postgres13
    description: example
    parameter:
      - name: application_name
        value: "example"
        applyMethod: immediate
---