apiVersion: rds.aws.kubedb.com/v1alpha1
kind: ProxyEndpoint
metadata:
  name: example
  annotations:
    upjet.kubedb.com/manual-intervention: "This resource has a reference to Proxy, which needs manual intervention."
spec:
  forProvider:
    region: us-east-2
    dbProxyName: example
    targetRole: READ_ONLY
    vpcSubnetIds:
      - subnet-0546de20b40a2c0c1
      - subnet-030de9d358df790ad
      - subnet-09c2fc96a4cd866a7
  providerConfigRef:
    name: default


---
# apiVersion: rds.aws.kubedb.com/v1alpha1
# kind: Proxy
# metadata:
#   name: example
#   annotations:
#     upjet.kubedb.com/manual-intervention: "This resource has a secret reference."
# spec:
#   forProvider:
#     region: us-east-2
#     auth:
#       - authScheme: SECRETS
#         description: example
#         iamAuth: DISABLED
#         secretArn: arn:aws:secretsmanager:us-east-2:your-iam-id:secret:rds-proxy-arm-yNkcwm
#     debugLogging: false
#     engineFamily: POSTGRESQL
#     idleClientTimeout: 1800
#     requireTls: true
#     roleArn: arn:aws:iam::your-iam-id:role/rds-proxy-role-arm
#     tags:
#       Key: value
#       Name: example
#     vpcSubnetIds:
#       - subnet-0c4b2417753007c1b
#       - subnet-013473289d844fd55
#       - subnet-0fc32c6ad4ac9f12b