apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/table
  labels:
    testing.kubedb.com/example-name: mytable
  name: mytable
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    region: us-east-2
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
    billingMode: PAY_PER_REQUEST

---
apiVersion: kinesis.aws.kubedb.com/v1alpha1
kind: Stream
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/kinesisstreamingdestination
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    shardCount: 1

---

apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: KinesisStreamingDestination
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/kinesisstreamingdestination
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    streamArnRef:
      name: example
    tableNameRef:
      name: mytable

---