apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/table
  labels:
    testing.kubedb.com/example-name: mytable
  name: mytable
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    region: us-east-2
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
    billingMode: PAY_PER_REQUEST

---
apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: TableItem
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/tableitem
  labels:
    testing.kubedb.com/example-name: mytable
  name: example
spec:
  forProvider:
    hashKey: exampleHashKey
    item: |
      {
        "exampleHashKey": {"S": "something"},
        "one": {"N": "11111"},
        "two": {"N": "22222"},
        "three": {"N": "33333"},
        "four": {"N": "44444"}
      }
    region: us-east-2
    tableNameRef:
      name: mytable

---