
apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: Tag
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/tag
  labels:
    testing.kubedb.com/example-name: test
  name: example
spec:
  forProvider:
    key: testkey
    region: us-east-2
    resourceArn: arn:aws:dynamodb:us-east-2:452618475015:table/mytable
    value: testvalue

---