
# We can deploy globaltable or tablereplica at a time. Both won't work together.
apiVersion: dynamodb.aws.kubedb.com/v1alpha1
kind: GlobalTable
metadata:
  annotations:
    meta.kubedb.com/example-id: dynamodb/v1alpha1/globaltable
  labels:
    testing.kubedb.com/example-name: mytable
  name: mytable
spec:
  forProvider:
    region: us-east-1
    replica:
      - regionName: us-east-2

---