apiVersion: elasticsearch.aws.kubedb.com/v1alpha1
kind: Domain
metadata:
  annotations:
    meta.kubedb.com/example-id: elasticsearch/v1alpha1/domain
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    clusterConfig:
    - instanceType: r4.large.elasticsearch
    elasticsearchVersion: "7.10"
    region: us-west-1
    tags:
      Domain: TestDomain
